# tcp setting
tcp:
  server:
    ip: 172.30.1.42
    port: 10001
    acceptIpSet: [] # empty = allow all
    interval:
      sessionList: 10 # printout session list interval
  client:
    ip: 172.30.1.42
    port: 10002
    sampleFile: sample.txt
    interval:
      sampleLog: 3

# udp setting
udp:
  encoding: UTF-8
  server:
    ip: 172.30.1.42
    port: 514
    bufferSize: 8192
    acceptIpSet: [] # empty = allow all
    interval:
      sessionList: 10 # printout session list interval
  client:
    ip: 172.30.1.42
    port: 5114
    sampleFile: sample.txt
    interval: 
      sampleLog: 3

# log generator setting
log:
  interval: 10
  sampleFile: sample.txt
  outputFile: test.log